import { StyleSheet, Platform, Dimensions } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F9FAFB" },
  header: { backgroundColor: "#fff", padding: 16, paddingTop: 24 },
  headerTitle: { fontSize: 22, fontWeight: "700", marginBottom: 16 },
  tabs: { flexDirection: "row", marginBottom: 16 },
  tabButton: { marginRight: 20, paddingBottom: 6 },
  tabText: { fontSize: 14, color: "#6B7280" },
  activeTab: { borderBottomWidth: 0, borderColor: "#111" },
  activeTabText: { color: "#111", fontWeight: "600" },
  addNewBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "#E5E7EB",
    borderRadius: 9999,
    marginRight: 8,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "#fff",
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: "#111",
    borderColor: "#111",
  },
  filterText: { color: "#374151" },
  filterTextActive: { color: "#fff" },
  dropdownFilter: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "#fff",
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginRight: 8,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    flex: 1,
    marginHorizontal: 4,
    elevation: Platform.OS === "android" ? 2 : 0,
  },
  image: { width: "100%", height: 160, resizeMode: "cover" },
  bookmarkBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 20,
    padding: 6,
  },
  plusBtn: {
    position: "absolute",
    bottom: 8,
    right: 8,
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 6,
    elevation: Platform.OS === "android" ? 2 : 0,
  },
  cardContent: { padding: 12 },
  categoryRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  categoryIcon: { fontSize: 14 },
  categoryTag: {
    borderRadius: 9999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 6,
  },
  categoryText: { fontSize: 10, fontWeight: "500" },
  itemName: { fontSize: 13, fontWeight: "500", color: "#111" },

  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderColor: "#E5E7EB",
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 14,
  },
  navBtn: { padding: 8 },
  squareBox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: "#111",
    borderRadius: 4,
  },

  // bottom sheet / modal styles
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
    zIndex: 50,
  },
  sheetContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    zIndex: 60,
    paddingHorizontal: 20,
    paddingTop: 10,
    minHeight: 260,
    maxHeight: 520,
  },
  sheetHandle: {
    width: 48,
    height: 6,
    backgroundColor: "#E5E7EB",
    borderRadius: 999,
    alignSelf: "center",
    marginVertical: 8,
  },
  sheetTitle: { fontSize: 16, fontWeight: "700", marginBottom: 12, color: "#111" },
  sheetList: { paddingBottom: 6 },
  sheetRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 6,
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: "#F3F4F6",
  },
  sheetRowText: { fontSize: 15, color: "#111" },
  check: { color: "#111", fontWeight: "700" },

  // color swatches
  colorGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  colorSwatchWrap: {
    width: (width - 64) / 3,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  swatch: {
    width: 44,
    height: 44,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: "transparent",
    marginBottom: 8,
  },
  colorLabel: { fontSize: 13, color: "#374151" },
  sheetCloseBtn: {
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
  },
  sheetCloseText: { color: "#111", fontWeight: "600" },

  // mini swatch
  miniSwatch: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  miniSwatchText: { marginLeft: 8 },
});
